[tools]
node = "lts"
bun = "latest"               # package manager
go = "latest"
usage = "latest"
"npm:opencode-ai" = "latest" # ai coding agent
# "npm:agent-browser" = "latest" # browser automation cli
lazygit = "latest"                             # git tui
glow = "latest"                                # markdown preview - used by nb
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/hmans/beans" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"go:github.com/maaslalani/slides" = "latest"
"npm:defuddle" = "latest"
rust = "latest"
# qry
"go:github.com/justestif/qry" = "latest"
"go:github.com/justestif/qry/adapters/qry-adapter-ddg-scrape" = "latest"
"go:github.com/justestif/qry/adapters/qry-adapter-exa" = "latest"
"go:github.com/justestif/qry/adapters/qry-adapter-brave-scrape" = "latest"
television = "latest"

[hooks]
enter = "mise install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
locked = false
env_shell_expand = true
