[tools]
node = "lts"
bun = "latest"
go = "latest"
rust = "latest"
usage = "latest"
opencode = "latest"
pi = "latest"
lazygit = "latest"
glow = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/hmans/beans" = "latest"
"npm:defuddle" = "latest"
"go:github.com/justestif/qry" = "latest"
television = "latest"
bat = "latest"
"npm:nb.sh" = "latest"
"npm:@justestif/lasso" = "latest"

# [hooks]
# enter = "mise install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
locked = false
env_shell_expand = true
