[tools]
node = "lts"
bun = "latest"               # package manager
go = "latest"
usage = "latest"
opencode = "latest"
pi = "latest"
# "npm:agent-browser" = "latest" # browser automation cli
lazygit = "latest"                           # git tui
glow = "latest"                              # markdown preview - used by nb
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/hmans/beans" = "latest"
"go:github.com/maaslalani/slides" = "latest"
"npm:defuddle" = "latest"
rust = "latest"
"go:github.com/justestif/qry" = "latest"
television = "latest"

[hooks]
enter = "mise install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
locked = false
env_shell_expand = true
