[env]
EDITOR = "nvim"

[general]
import = [
  "~/.config/alacritty/themes/tokyo-night.toml",
  "~/.config/alacritty/themes/tokyo-night-day.toml",
]

[font]
normal = { family = "ZedMono Nerd Font Mono", style = "Regular" }
size = 13

[window]
decorations = "None"
option_as_alt = "Both"

[terminal]
shell = "fish"

# problem
# 1. the theme does switch between dark/light automatically
