general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
EDITOR = "nvim"

[font]
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
size = 14

[window]
option_as_alt = "Both"
decorations = "None"
