gui:
  showCommandLog: false

os:
  edit: 'nvim {{filename}}'
  editAtLine: 'nvim +{{line}} {{filename}}'
  editAtLineAndWait: 'nvim --remote-wait +{{line}} {{filename}}'
  editInTerminal: true

git:
  paging:
    colorArg: always
    pager: diff-so-fancy

keybinding:
  universal:
    quit: "<c-q>"
