complete -c pi-sandbox -s h -l help -d 'Show wrapper help'
complete -c pi-sandbox -s C -l cwd -r -d 'Set working directory'
complete -c pi-sandbox -l allow-read -r -d 'Allow filesystem reads (repeatable)'
complete -c pi-sandbox -l allow-write -r -d 'Allow filesystem writes (repeatable)'
complete -c pi-sandbox -l allow-net -r -d 'Reserved network grant (currently fails closed)'
complete -c pi-sandbox -l allow-env -r -d 'Allow inherited environment name/glob (repeatable)'
complete -c pi-sandbox -l deny-read -d 'Deny filesystem reads'
complete -c pi-sandbox -l deny-write -d 'Deny filesystem writes'
complete -c pi-sandbox -l deny-net -d 'Deny network access'
complete -c pi-sandbox -l deny-env -d 'Deny environment inheritance'
complete -c pi-sandbox -l deny-all -d 'Deny reads, writes, network, and environment'
complete -c pi-sandbox -l state-dir -r -d 'Create isolated Pi state at path'
complete -c pi-sandbox -l keep-state -d 'Retain isolated Pi state'
complete -c pi-sandbox -l dry-run -d 'Print escaped command without executing'
