complete -c pi-sandbox -n '__fish_use_subcommand' -f -a skills -d 'Load pi-sandbox usage guides'
complete -c pi-sandbox -s h -l help -d 'Show wrapper help'
complete -c pi-sandbox -s C -l cwd -r -d 'Set working directory'
complete -c pi-sandbox -l allow-read -r -d 'Allow filesystem reads (repeatable)'
complete -c pi-sandbox -l allow-write -r -d 'Allow filesystem writes (repeatable)'
complete -c pi-sandbox -l allow-net -r -a all -d 'Allow unrestricted outbound network access'
complete -c pi-sandbox -l allow-net-host -r -d 'Allow HTTPS CONNECT to hostname rule (repeatable)'
complete -c pi-sandbox -l deny-net-host -r -d 'Deny HTTPS CONNECT to hostname rule (repeatable)'
complete -c pi-sandbox -l allow-env -r -d 'Allow inherited environment name/glob (repeatable)'
complete -c pi-sandbox -l allow-command -r -d 'Allow matching Bash commands (repeatable)'
complete -c pi-sandbox -l ask-command -r -d 'Ask before matching Bash commands (repeatable)'
complete -c pi-sandbox -l deny-command -r -d 'Deny matching Bash commands (repeatable)'
complete -c pi-sandbox -l deny-read -d 'Deny filesystem reads'
complete -c pi-sandbox -l deny-write -d 'Deny filesystem writes'
complete -c pi-sandbox -l deny-net -d 'Deny network access'
complete -c pi-sandbox -l deny-env -d 'Deny environment inheritance'
complete -c pi-sandbox -l deny-all -d 'Deny reads, writes, network, and environment'
complete -c pi-sandbox -l state-dir -r -d 'Create isolated Pi state at path'
complete -c pi-sandbox -l keep-state -d 'Retain isolated Pi state'
complete -c pi-sandbox -l share-auth -d 'Mount host Pi auth read/write'
complete -c pi-sandbox -l dry-run -d 'Print escaped command without executing'
