browser: 
  headless: false
  enabled: false
defaultThinkingLevel: minimal
hideThinkingBlock: true
compaction: 
  strategy: handoff
  handoffSaveToDisk: true
  thresholdPercent: -1
  thresholdTokens: -1
memories: 
  enabled: true
edit: 
  mode: vim
  fuzzyMatch: true
lsp: 
  formatOnWrite: true
renderMermaid: 
  enabled: true
github: 
  enabled: true
async: 
  enabled: false
modelRoles: 
  default: zai/glm-5.1
stt: 
  enabled: false
startup: 
  quiet: false
commands: 
  enableClaudeUser: false
  enableClaudeProject: false
  enableOpencodeUser: false
  enableOpencodeProject: false
task: 
  eager: false
colorBlindMode: false
display: 
  showTokenUsage: false
contextPromotion: 
  enabled: false
memory: 
  backend: local
notebook: 
  enabled: false
debug: 
  enabled: false
tools: 
  intentTracing: false
mcp: 
  enableProjectConfig: false
secrets: 
  enabled: false
exa: 
  enableResearcher: false